name: cqrs_mediator
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/mo-ah-dawood/cqrs_mediator

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.20.1
  lints: ^1.0.0
